
### getCarsBlock()
GET http://localhost:8081/cars/block
Content-Type: application/json

### getCar()
GET http://localhost:8081/car
Content-Type: application/json

### getCars()
GET http://localhost:8081/cars
Content-Type: application/json

### getCarStream()
GET http://localhost:8081/cars
Accept: application/stream+json
